/**
 * World Countries Master — 195 UN-recognised countries
 * ISO 3166-1 (2024) codes + ITU-T E.164 phone codes
 */

export interface WorldCountry {
  /** ISO 3166-1 Alpha-2 */
  alpha2: string;
  /** ISO 3166-1 Alpha-3 */
  alpha3: string;
  /** ISO 3166-1 Numeric (zero-padded string) */
  numeric: string;
  /** Official English short name */
  name: string;
  /** ITU calling code, e.g. "+91" */
  phoneCode: string;
}

export const WORLD_COUNTRIES: WorldCountry[] = [
  { alpha2: 'AF', alpha3: 'AFG', numeric: '004', name: 'Afghanistan', phoneCode: '+93' },
  { alpha2: 'AL', alpha3: 'ALB', numeric: '008', name: 'Albania', phoneCode: '+355' },
  { alpha2: 'DZ', alpha3: 'DZA', numeric: '012', name: 'Algeria', phoneCode: '+213' },
  { alpha2: 'AD', alpha3: 'AND', numeric: '020', name: 'Andorra', phoneCode: '+376' },
  { alpha2: 'AO', alpha3: 'AGO', numeric: '024', name: 'Angola', phoneCode: '+244' },
  { alpha2: 'AG', alpha3: 'ATG', numeric: '028', name: 'Antigua and Barbuda', phoneCode: '+1-268' },
  { alpha2: 'AR', alpha3: 'ARG', numeric: '032', name: 'Argentina', phoneCode: '+54' },
  { alpha2: 'AM', alpha3: 'ARM', numeric: '051', name: 'Armenia', phoneCode: '+374' },
  { alpha2: 'AU', alpha3: 'AUS', numeric: '036', name: 'Australia', phoneCode: '+61' },
  { alpha2: 'AT', alpha3: 'AUT', numeric: '040', name: 'Austria', phoneCode: '+43' },
  { alpha2: 'AZ', alpha3: 'AZE', numeric: '031', name: 'Azerbaijan', phoneCode: '+994' },
  { alpha2: 'BS', alpha3: 'BHS', numeric: '044', name: 'Bahamas', phoneCode: '+1-242' },
  { alpha2: 'BH', alpha3: 'BHR', numeric: '048', name: 'Bahrain', phoneCode: '+973' },
  { alpha2: 'BD', alpha3: 'BGD', numeric: '050', name: 'Bangladesh', phoneCode: '+880' },
  { alpha2: 'BB', alpha3: 'BRB', numeric: '052', name: 'Barbados', phoneCode: '+1-246' },
  { alpha2: 'BY', alpha3: 'BLR', numeric: '112', name: 'Belarus', phoneCode: '+375' },
  { alpha2: 'BE', alpha3: 'BEL', numeric: '056', name: 'Belgium', phoneCode: '+32' },
  { alpha2: 'BZ', alpha3: 'BLZ', numeric: '084', name: 'Belize', phoneCode: '+501' },
  { alpha2: 'BJ', alpha3: 'BEN', numeric: '204', name: 'Benin', phoneCode: '+229' },
  { alpha2: 'BT', alpha3: 'BTN', numeric: '064', name: 'Bhutan', phoneCode: '+975' },
  { alpha2: 'BO', alpha3: 'BOL', numeric: '068', name: 'Bolivia', phoneCode: '+591' },
  { alpha2: 'BA', alpha3: 'BIH', numeric: '070', name: 'Bosnia and Herzegovina', phoneCode: '+387' },
  { alpha2: 'BW', alpha3: 'BWA', numeric: '072', name: 'Botswana', phoneCode: '+267' },
  { alpha2: 'BR', alpha3: 'BRA', numeric: '076', name: 'Brazil', phoneCode: '+55' },
  { alpha2: 'BN', alpha3: 'BRN', numeric: '096', name: 'Brunei', phoneCode: '+673' },
  { alpha2: 'BG', alpha3: 'BGR', numeric: '100', name: 'Bulgaria', phoneCode: '+359' },
  { alpha2: 'BF', alpha3: 'BFA', numeric: '854', name: 'Burkina Faso', phoneCode: '+226' },
  { alpha2: 'BI', alpha3: 'BDI', numeric: '108', name: 'Burundi', phoneCode: '+257' },
  { alpha2: 'CV', alpha3: 'CPV', numeric: '132', name: 'Cabo Verde', phoneCode: '+238' },
  { alpha2: 'KH', alpha3: 'KHM', numeric: '116', name: 'Cambodia', phoneCode: '+855' },
  { alpha2: 'CM', alpha3: 'CMR', numeric: '120', name: 'Cameroon', phoneCode: '+237' },
  { alpha2: 'CA', alpha3: 'CAN', numeric: '124', name: 'Canada', phoneCode: '+1' },
  { alpha2: 'CF', alpha3: 'CAF', numeric: '140', name: 'Central African Republic', phoneCode: '+236' },
  { alpha2: 'TD', alpha3: 'TCD', numeric: '148', name: 'Chad', phoneCode: '+235' },
  { alpha2: 'CL', alpha3: 'CHL', numeric: '152', name: 'Chile', phoneCode: '+56' },
  { alpha2: 'CN', alpha3: 'CHN', numeric: '156', name: 'China', phoneCode: '+86' },
  { alpha2: 'CO', alpha3: 'COL', numeric: '170', name: 'Colombia', phoneCode: '+57' },
  { alpha2: 'KM', alpha3: 'COM', numeric: '174', name: 'Comoros', phoneCode: '+269' },
  { alpha2: 'CG', alpha3: 'COG', numeric: '178', name: 'Congo', phoneCode: '+242' },
  { alpha2: 'CD', alpha3: 'COD', numeric: '180', name: 'Congo, Dem. Rep.', phoneCode: '+243' },
  { alpha2: 'CR', alpha3: 'CRI', numeric: '188', name: 'Costa Rica', phoneCode: '+506' },
  { alpha2: 'CI', alpha3: 'CIV', numeric: '384', name: "Cote d'Ivoire", phoneCode: '+225' },
  { alpha2: 'HR', alpha3: 'HRV', numeric: '191', name: 'Croatia', phoneCode: '+385' },
  { alpha2: 'CU', alpha3: 'CUB', numeric: '192', name: 'Cuba', phoneCode: '+53' },
  { alpha2: 'CY', alpha3: 'CYP', numeric: '196', name: 'Cyprus', phoneCode: '+357' },
  { alpha2: 'CZ', alpha3: 'CZE', numeric: '203', name: 'Czech Republic', phoneCode: '+420' },
  { alpha2: 'DK', alpha3: 'DNK', numeric: '208', name: 'Denmark', phoneCode: '+45' },
  { alpha2: 'DJ', alpha3: 'DJI', numeric: '262', name: 'Djibouti', phoneCode: '+253' },
  { alpha2: 'DM', alpha3: 'DMA', numeric: '212', name: 'Dominica', phoneCode: '+1-767' },
  { alpha2: 'DO', alpha3: 'DOM', numeric: '214', name: 'Dominican Republic', phoneCode: '+1-809' },
  { alpha2: 'EC', alpha3: 'ECU', numeric: '218', name: 'Ecuador', phoneCode: '+593' },
  { alpha2: 'EG', alpha3: 'EGY', numeric: '818', name: 'Egypt', phoneCode: '+20' },
  { alpha2: 'SV', alpha3: 'SLV', numeric: '222', name: 'El Salvador', phoneCode: '+503' },
  { alpha2: 'GQ', alpha3: 'GNQ', numeric: '226', name: 'Equatorial Guinea', phoneCode: '+240' },
  { alpha2: 'ER', alpha3: 'ERI', numeric: '232', name: 'Eritrea', phoneCode: '+291' },
  { alpha2: 'EE', alpha3: 'EST', numeric: '233', name: 'Estonia', phoneCode: '+372' },
  { alpha2: 'SZ', alpha3: 'SWZ', numeric: '748', name: 'Eswatini', phoneCode: '+268' },
  { alpha2: 'ET', alpha3: 'ETH', numeric: '231', name: 'Ethiopia', phoneCode: '+251' },
  { alpha2: 'FJ', alpha3: 'FJI', numeric: '242', name: 'Fiji', phoneCode: '+679' },
  { alpha2: 'FI', alpha3: 'FIN', numeric: '246', name: 'Finland', phoneCode: '+358' },
  { alpha2: 'FR', alpha3: 'FRA', numeric: '250', name: 'France', phoneCode: '+33' },
  { alpha2: 'GA', alpha3: 'GAB', numeric: '266', name: 'Gabon', phoneCode: '+241' },
  { alpha2: 'GM', alpha3: 'GMB', numeric: '270', name: 'Gambia', phoneCode: '+220' },
  { alpha2: 'GE', alpha3: 'GEO', numeric: '268', name: 'Georgia', phoneCode: '+995' },
  { alpha2: 'DE', alpha3: 'DEU', numeric: '276', name: 'Germany', phoneCode: '+49' },
  { alpha2: 'GH', alpha3: 'GHA', numeric: '288', name: 'Ghana', phoneCode: '+233' },
  { alpha2: 'GR', alpha3: 'GRC', numeric: '300', name: 'Greece', phoneCode: '+30' },
  { alpha2: 'GD', alpha3: 'GRD', numeric: '308', name: 'Grenada', phoneCode: '+1-473' },
  { alpha2: 'GT', alpha3: 'GTM', numeric: '320', name: 'Guatemala', phoneCode: '+502' },
  { alpha2: 'GN', alpha3: 'GIN', numeric: '324', name: 'Guinea', phoneCode: '+224' },
  { alpha2: 'GW', alpha3: 'GNB', numeric: '624', name: 'Guinea-Bissau', phoneCode: '+245' },
  { alpha2: 'GY', alpha3: 'GUY', numeric: '328', name: 'Guyana', phoneCode: '+592' },
  { alpha2: 'HT', alpha3: 'HTI', numeric: '332', name: 'Haiti', phoneCode: '+509' },
  { alpha2: 'HN', alpha3: 'HND', numeric: '340', name: 'Honduras', phoneCode: '+504' },
  { alpha2: 'HU', alpha3: 'HUN', numeric: '348', name: 'Hungary', phoneCode: '+36' },
  { alpha2: 'IS', alpha3: 'ISL', numeric: '352', name: 'Iceland', phoneCode: '+354' },
  { alpha2: 'IN', alpha3: 'IND', numeric: '356', name: 'India', phoneCode: '+91' },
  { alpha2: 'ID', alpha3: 'IDN', numeric: '360', name: 'Indonesia', phoneCode: '+62' },
  { alpha2: 'IR', alpha3: 'IRN', numeric: '364', name: 'Iran', phoneCode: '+98' },
  { alpha2: 'IQ', alpha3: 'IRQ', numeric: '368', name: 'Iraq', phoneCode: '+964' },
  { alpha2: 'IE', alpha3: 'IRL', numeric: '372', name: 'Ireland', phoneCode: '+353' },
  { alpha2: 'IL', alpha3: 'ISR', numeric: '376', name: 'Israel', phoneCode: '+972' },
  { alpha2: 'IT', alpha3: 'ITA', numeric: '380', name: 'Italy', phoneCode: '+39' },
  { alpha2: 'JM', alpha3: 'JAM', numeric: '388', name: 'Jamaica', phoneCode: '+1-876' },
  { alpha2: 'JP', alpha3: 'JPN', numeric: '392', name: 'Japan', phoneCode: '+81' },
  { alpha2: 'JO', alpha3: 'JOR', numeric: '400', name: 'Jordan', phoneCode: '+962' },
  { alpha2: 'KZ', alpha3: 'KAZ', numeric: '398', name: 'Kazakhstan', phoneCode: '+7' },
  { alpha2: 'KE', alpha3: 'KEN', numeric: '404', name: 'Kenya', phoneCode: '+254' },
  { alpha2: 'KI', alpha3: 'KIR', numeric: '296', name: 'Kiribati', phoneCode: '+686' },
  { alpha2: 'KP', alpha3: 'PRK', numeric: '408', name: 'Korea, North', phoneCode: '+850' },
  { alpha2: 'KR', alpha3: 'KOR', numeric: '410', name: 'Korea, South', phoneCode: '+82' },
  { alpha2: 'KW', alpha3: 'KWT', numeric: '414', name: 'Kuwait', phoneCode: '+965' },
  { alpha2: 'KG', alpha3: 'KGZ', numeric: '417', name: 'Kyrgyzstan', phoneCode: '+996' },
  { alpha2: 'LA', alpha3: 'LAO', numeric: '418', name: 'Laos', phoneCode: '+856' },
  { alpha2: 'LV', alpha3: 'LVA', numeric: '428', name: 'Latvia', phoneCode: '+371' },
  { alpha2: 'LB', alpha3: 'LBN', numeric: '422', name: 'Lebanon', phoneCode: '+961' },
  { alpha2: 'LS', alpha3: 'LSO', numeric: '426', name: 'Lesotho', phoneCode: '+266' },
  { alpha2: 'LR', alpha3: 'LBR', numeric: '430', name: 'Liberia', phoneCode: '+231' },
  { alpha2: 'LY', alpha3: 'LBY', numeric: '434', name: 'Libya', phoneCode: '+218' },
  { alpha2: 'LI', alpha3: 'LIE', numeric: '438', name: 'Liechtenstein', phoneCode: '+423' },
  { alpha2: 'LT', alpha3: 'LTU', numeric: '440', name: 'Lithuania', phoneCode: '+370' },
  { alpha2: 'LU', alpha3: 'LUX', numeric: '442', name: 'Luxembourg', phoneCode: '+352' },
  { alpha2: 'MG', alpha3: 'MDG', numeric: '450', name: 'Madagascar', phoneCode: '+261' },
  { alpha2: 'MW', alpha3: 'MWI', numeric: '454', name: 'Malawi', phoneCode: '+265' },
  { alpha2: 'MY', alpha3: 'MYS', numeric: '458', name: 'Malaysia', phoneCode: '+60' },
  { alpha2: 'MV', alpha3: 'MDV', numeric: '462', name: 'Maldives', phoneCode: '+960' },
  { alpha2: 'ML', alpha3: 'MLI', numeric: '466', name: 'Mali', phoneCode: '+223' },
  { alpha2: 'MT', alpha3: 'MLT', numeric: '470', name: 'Malta', phoneCode: '+356' },
  { alpha2: 'MH', alpha3: 'MHL', numeric: '584', name: 'Marshall Islands', phoneCode: '+692' },
  { alpha2: 'MR', alpha3: 'MRT', numeric: '478', name: 'Mauritania', phoneCode: '+222' },
  { alpha2: 'MU', alpha3: 'MUS', numeric: '480', name: 'Mauritius', phoneCode: '+230' },
  { alpha2: 'MX', alpha3: 'MEX', numeric: '484', name: 'Mexico', phoneCode: '+52' },
  { alpha2: 'FM', alpha3: 'FSM', numeric: '583', name: 'Micronesia', phoneCode: '+691' },
  { alpha2: 'MD', alpha3: 'MDA', numeric: '498', name: 'Moldova', phoneCode: '+373' },
  { alpha2: 'MC', alpha3: 'MCO', numeric: '492', name: 'Monaco', phoneCode: '+377' },
  { alpha2: 'MN', alpha3: 'MNG', numeric: '496', name: 'Mongolia', phoneCode: '+976' },
  { alpha2: 'ME', alpha3: 'MNE', numeric: '499', name: 'Montenegro', phoneCode: '+382' },
  { alpha2: 'MA', alpha3: 'MAR', numeric: '504', name: 'Morocco', phoneCode: '+212' },
  { alpha2: 'MZ', alpha3: 'MOZ', numeric: '508', name: 'Mozambique', phoneCode: '+258' },
  { alpha2: 'MM', alpha3: 'MMR', numeric: '104', name: 'Myanmar', phoneCode: '+95' },
  { alpha2: 'NA', alpha3: 'NAM', numeric: '516', name: 'Namibia', phoneCode: '+264' },
  { alpha2: 'NR', alpha3: 'NRU', numeric: '520', name: 'Nauru', phoneCode: '+674' },
  { alpha2: 'NP', alpha3: 'NPL', numeric: '524', name: 'Nepal', phoneCode: '+977' },
  { alpha2: 'NL', alpha3: 'NLD', numeric: '528', name: 'Netherlands', phoneCode: '+31' },
  { alpha2: 'NZ', alpha3: 'NZL', numeric: '554', name: 'New Zealand', phoneCode: '+64' },
  { alpha2: 'NI', alpha3: 'NIC', numeric: '558', name: 'Nicaragua', phoneCode: '+505' },
  { alpha2: 'NE', alpha3: 'NER', numeric: '562', name: 'Niger', phoneCode: '+227' },
  { alpha2: 'NG', alpha3: 'NGA', numeric: '566', name: 'Nigeria', phoneCode: '+234' },
  { alpha2: 'MK', alpha3: 'MKD', numeric: '807', name: 'North Macedonia', phoneCode: '+389' },
  { alpha2: 'NO', alpha3: 'NOR', numeric: '578', name: 'Norway', phoneCode: '+47' },
  { alpha2: 'OM', alpha3: 'OMN', numeric: '512', name: 'Oman', phoneCode: '+968' },
  { alpha2: 'PK', alpha3: 'PAK', numeric: '586', name: 'Pakistan', phoneCode: '+92' },
  { alpha2: 'PW', alpha3: 'PLW', numeric: '585', name: 'Palau', phoneCode: '+680' },
  { alpha2: 'PA', alpha3: 'PAN', numeric: '591', name: 'Panama', phoneCode: '+507' },
  { alpha2: 'PG', alpha3: 'PNG', numeric: '598', name: 'Papua New Guinea', phoneCode: '+675' },
  { alpha2: 'PY', alpha3: 'PRY', numeric: '600', name: 'Paraguay', phoneCode: '+595' },
  { alpha2: 'PE', alpha3: 'PER', numeric: '604', name: 'Peru', phoneCode: '+51' },
  { alpha2: 'PH', alpha3: 'PHL', numeric: '608', name: 'Philippines', phoneCode: '+63' },
  { alpha2: 'PL', alpha3: 'POL', numeric: '616', name: 'Poland', phoneCode: '+48' },
  { alpha2: 'PT', alpha3: 'PRT', numeric: '620', name: 'Portugal', phoneCode: '+351' },
  { alpha2: 'QA', alpha3: 'QAT', numeric: '634', name: 'Qatar', phoneCode: '+974' },
  { alpha2: 'RO', alpha3: 'ROU', numeric: '642', name: 'Romania', phoneCode: '+40' },
  { alpha2: 'RU', alpha3: 'RUS', numeric: '643', name: 'Russia', phoneCode: '+7' },
  { alpha2: 'RW', alpha3: 'RWA', numeric: '646', name: 'Rwanda', phoneCode: '+250' },
  { alpha2: 'KN', alpha3: 'KNA', numeric: '659', name: 'Saint Kitts and Nevis', phoneCode: '+1-869' },
  { alpha2: 'LC', alpha3: 'LCA', numeric: '662', name: 'Saint Lucia', phoneCode: '+1-758' },
  { alpha2: 'VC', alpha3: 'VCT', numeric: '670', name: 'Saint Vincent and the Grenadines', phoneCode: '+1-784' },
  { alpha2: 'WS', alpha3: 'WSM', numeric: '882', name: 'Samoa', phoneCode: '+685' },
  { alpha2: 'SM', alpha3: 'SMR', numeric: '674', name: 'San Marino', phoneCode: '+378' },
  { alpha2: 'ST', alpha3: 'STP', numeric: '678', name: 'Sao Tome and Principe', phoneCode: '+239' },
  { alpha2: 'SA', alpha3: 'SAU', numeric: '682', name: 'Saudi Arabia', phoneCode: '+966' },
  { alpha2: 'SN', alpha3: 'SEN', numeric: '686', name: 'Senegal', phoneCode: '+221' },
  { alpha2: 'RS', alpha3: 'SRB', numeric: '688', name: 'Serbia', phoneCode: '+381' },
  { alpha2: 'SC', alpha3: 'SYC', numeric: '690', name: 'Seychelles', phoneCode: '+248' },
  { alpha2: 'SL', alpha3: 'SLE', numeric: '694', name: 'Sierra Leone', phoneCode: '+232' },
  { alpha2: 'SG', alpha3: 'SGP', numeric: '702', name: 'Singapore', phoneCode: '+65' },
  { alpha2: 'SK', alpha3: 'SVK', numeric: '703', name: 'Slovakia', phoneCode: '+421' },
  { alpha2: 'SI', alpha3: 'SVN', numeric: '705', name: 'Slovenia', phoneCode: '+386' },
  { alpha2: 'SB', alpha3: 'SLB', numeric: '090', name: 'Solomon Islands', phoneCode: '+677' },
  { alpha2: 'SO', alpha3: 'SOM', numeric: '706', name: 'Somalia', phoneCode: '+252' },
  { alpha2: 'ZA', alpha3: 'ZAF', numeric: '710', name: 'South Africa', phoneCode: '+27' },
  { alpha2: 'SS', alpha3: 'SSD', numeric: '728', name: 'South Sudan', phoneCode: '+211' },
  { alpha2: 'ES', alpha3: 'ESP', numeric: '724', name: 'Spain', phoneCode: '+34' },
  { alpha2: 'LK', alpha3: 'LKA', numeric: '144', name: 'Sri Lanka', phoneCode: '+94' },
  { alpha2: 'SD', alpha3: 'SDN', numeric: '729', name: 'Sudan', phoneCode: '+249' },
  { alpha2: 'SR', alpha3: 'SUR', numeric: '740', name: 'Suriname', phoneCode: '+597' },
  { alpha2: 'SE', alpha3: 'SWE', numeric: '752', name: 'Sweden', phoneCode: '+46' },
  { alpha2: 'CH', alpha3: 'CHE', numeric: '756', name: 'Switzerland', phoneCode: '+41' },
  { alpha2: 'SY', alpha3: 'SYR', numeric: '760', name: 'Syria', phoneCode: '+963' },
  { alpha2: 'TW', alpha3: 'TWN', numeric: '158', name: 'Taiwan', phoneCode: '+886' },
  { alpha2: 'TJ', alpha3: 'TJK', numeric: '762', name: 'Tajikistan', phoneCode: '+992' },
  { alpha2: 'TZ', alpha3: 'TZA', numeric: '834', name: 'Tanzania', phoneCode: '+255' },
  { alpha2: 'TH', alpha3: 'THA', numeric: '764', name: 'Thailand', phoneCode: '+66' },
  { alpha2: 'TL', alpha3: 'TLS', numeric: '626', name: 'Timor-Leste', phoneCode: '+670' },
  { alpha2: 'TG', alpha3: 'TGO', numeric: '768', name: 'Togo', phoneCode: '+228' },
  { alpha2: 'TO', alpha3: 'TON', numeric: '776', name: 'Tonga', phoneCode: '+676' },
  { alpha2: 'TT', alpha3: 'TTO', numeric: '780', name: 'Trinidad and Tobago', phoneCode: '+1-868' },
  { alpha2: 'TN', alpha3: 'TUN', numeric: '788', name: 'Tunisia', phoneCode: '+216' },
  { alpha2: 'TR', alpha3: 'TUR', numeric: '792', name: 'Turkey', phoneCode: '+90' },
  { alpha2: 'TM', alpha3: 'TKM', numeric: '795', name: 'Turkmenistan', phoneCode: '+993' },
  { alpha2: 'TV', alpha3: 'TUV', numeric: '798', name: 'Tuvalu', phoneCode: '+688' },
  { alpha2: 'UG', alpha3: 'UGA', numeric: '800', name: 'Uganda', phoneCode: '+256' },
  { alpha2: 'UA', alpha3: 'UKR', numeric: '804', name: 'Ukraine', phoneCode: '+380' },
  { alpha2: 'AE', alpha3: 'ARE', numeric: '784', name: 'United Arab Emirates', phoneCode: '+971' },
  { alpha2: 'GB', alpha3: 'GBR', numeric: '826', name: 'United Kingdom', phoneCode: '+44' },
  { alpha2: 'US', alpha3: 'USA', numeric: '840', name: 'United States', phoneCode: '+1' },
  { alpha2: 'UY', alpha3: 'URY', numeric: '858', name: 'Uruguay', phoneCode: '+598' },
  { alpha2: 'UZ', alpha3: 'UZB', numeric: '860', name: 'Uzbekistan', phoneCode: '+998' },
  { alpha2: 'VU', alpha3: 'VUT', numeric: '548', name: 'Vanuatu', phoneCode: '+678' },
  { alpha2: 'VE', alpha3: 'VEN', numeric: '862', name: 'Venezuela', phoneCode: '+58' },
  { alpha2: 'VN', alpha3: 'VNM', numeric: '704', name: 'Vietnam', phoneCode: '+84' },
  { alpha2: 'YE', alpha3: 'YEM', numeric: '887', name: 'Yemen', phoneCode: '+967' },
  { alpha2: 'ZM', alpha3: 'ZMB', numeric: '894', name: 'Zambia', phoneCode: '+260' },
  { alpha2: 'ZW', alpha3: 'ZWE', numeric: '716', name: 'Zimbabwe', phoneCode: '+263' },
];

/** Fast lookup map: ISO Alpha-2 → WorldCountry */
export const COUNTRY_BY_ALPHA2: Record<string, WorldCountry> = Object.fromEntries(
  WORLD_COUNTRIES.map((c) => [c.alpha2, c]),
);
